### ISSUE TITLE
Unable to start GUI

### ISSUE THREAD

**Issue by wirelessmonkey** [dubbadhar/PCHWRM_Server#15]
> WARNING: Cannot access application main method: java.lang.NoSuchMethodException: PCHWRMServer.Main.main([Ljava.lang.String;)
> Launching application directly
> System.loadLibrary(javafx_font) succeeded
> System.loadLibrary(javafx_font_freetype) succeeded
> System.loadLibrary(javafx_font_pango) succeeded
> C
> Starting Server ...
> java.net.UnknownHostException: 192.168.1.24fdaa:bbcc:ddee:0:ac16:7552:a2f1:62d6: invalid IPv6 address
>         at java.base/java.net.InetAddress.getAllByName(Unknown Source)
>         at java.base/java.net.InetAddress.getAllByName(Unknown Source)
>         at java.base/java.net.InetAddress.getByName(Unknown Source)
>         at PCHWRMServer.monitor.startServer(monitor.java:62)
>         at PCHWRMServer.monitor$1.call(monitor.java:32)
>         at PCHWRMServer.monitor$1.call(monitor.java:26)
>         at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
>         at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> max rectangle texture cell size = 62
> wrap rectangle texture = 2 x 2
> ES2ResourceFactory: Prism - createStockShader: AlphaTexture_Color.frag
> ES2ResourceFactory: Prism - createStockShader: Texture_Color.frag
> ES2ResourceFactory: Prism - createStockShader: FillRoundRect_Color.frag
> new alphas with length = 4096
> ES2ResourceFactory: Prism - createStockShader: Solid_TextureRGB.frag
> new alphas with length = 20480
> ES2ResourceFactory: Prism - createStockShader: AlphaOne_Color.frag
> ES2ResourceFactory: Prism - createStockShader: DrawRoundRect_Color.frag
> ES2ResourceFactory: Prism - createStockShader: FillCircle_Color.frag
> ES2ResourceFactory: Prism - createStockShader: DrawCircle_Color.frag
> new alphas with length = 32768
> 

I have the above at the end of the code viewed on SSH

Screen displays "Listening for connection" and where it should display IP and port the numbers arent there, replaced by 'X'

Thoughts?

**Comment by keeganx** [comment]
I am having the save issue.  Where you able to resolve this?

> > WARNING: Cannot access application main method: java.lang.NoSuchMethodException: PCHWRMServer.Main.main([Ljava.lang.String;)
> > Launching application directly
> > System.loadLibrary(javafx_font) succeeded
> > System.loadLibrary(javafx_font_freetype) succeeded
> > System.loadLibrary(javafx_font_pango) succeeded
> > C
> > Starting Server ...
> > java.net.UnknownHostException: 192.168.1.24fdaa:bbcc:ddee:0:ac16:7552:a2f1:62d6: invalid IPv6 address
> > at java.base/java.net.InetAddress.getAllByName(Unknown Source)
> > at java.base/java.net.InetAddress.getAllByName(Unknown Source)
> > at java.base/java.net.InetAddress.getByName(Unknown Source)
> > at PCHWRMServer.monitor.startServer(monitor.java:62)
> > at PCHWRMServer.monitor$1.call(monitor.java:32)
> > at PCHWRMServer.monitor$1.call(monitor.java:26)
> > at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
> > at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> > at java.base/java.lang.Thread.run(Unknown Source)
> > max rectangle texture cell size = 62
> > wrap rectangle texture = 2 x 2
> > ES2ResourceFactory: Prism - createStockShader: AlphaTexture_Color.frag
> > ES2ResourceFactory: Prism - createStockShader: Texture_Color.frag
> > ES2ResourceFactory: Prism - createStockShader: FillRoundRect_Color.frag
> > new alphas with length = 4096
> > ES2ResourceFactory: Prism - createStockShader: Solid_TextureRGB.frag
> > new alphas with length = 20480
> > ES2ResourceFactory: Prism - createStockShader: AlphaOne_Color.frag
> > ES2ResourceFactory: Prism - createStockShader: DrawRoundRect_Color.frag
> > ES2ResourceFactory: Prism - createStockShader: FillCircle_Color.frag
> > ES2ResourceFactory: Prism - createStockShader: DrawCircle_Color.frag
> > new alphas with length = 32768
> 
> I have the above at the end of the code viewed on SSH
> 
> Screen displays "Listening for connection" and where it should display IP and port the numbers arent there, replaced by 'X'
> 
> Thoughts?

I am having the same issue.  Where you able to find a solution?

**Comment by bosskopp** [comment]
A quick workaround for Raspian is to disable IPv6, e.g.:

```
printf "\nnet.ipv6.conf.all.disable_ipv6=1\nnet.ipv6.conf.default.disable_ipv6=1\nnet.ipv6.conf.lo.disable_ipv6=1\nnet.ipv6.conf.eth0.disable_ipv6=1\n" | sudo tee -a /etc/sysctl.conf
printf "\nservice procps reload\n" | sudo tee -a /etc/rc.local
```
Don't forget to reboot afterwards.

**Comment by rnayabed** [comment]
Yes @bosskopp 's workaround is the fix :)
