### ISSUE TITLE
Failed to Add Service

### ISSUE THREAD

**Issue by bmxnate** [dubbadhar/PCHWRM_Server#2]
I have tried this on both vanilla Raspbian Lite and Raspbian Full, but I keep getting the following message when I try to run the server:

`**pi@hwm:~/PCHWRM_Server $ ./run**
JavaFX launchApplication method: launchMode=LM_CLASS
Prism pipeline init order: es2
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
System.loadLibrary(prism_es2_monocle) succeeded
        succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
System.loadLibrary(glass_monocle) succeeded
* failed to add service - already in use?`

There is not another instance of the service already in use, and I have tried other ports with the editConfig tool.  I don't believe it should matter, but I am trying to run this on a Pi 4b.  I have attached a picture of the output of htop, and I am open to any suggestions.

![htop](https://user-images.githubusercontent.com/63912193/79645168-a0fb3680-817b-11ea-904b-2da171f9fb9a.png)

**Comment by rnayabed** [comment]
Pi 4 has bad gpu drivers. This error is thrown by the GL driver. You could
run it using Xserver but then performance would be bad.

**Comment by bmxnate** [comment]
No worries there, I figured it was worth a shot.  The only other Pi I have in front of me is a Pi B v2 (single-core, 512MB RAM) and getting a modern JDK for the ARMv6 chip has proven difficult. Openjfx 11 is still available in the raspbian repo and I can get Zulu 11 JDK going, but it is still angry about the class file version being too high (58 vs. 55) from what it was compiled with.

> Error: LinkageError occurred while loading main class PCHWRMServer.Main
        java.lang.UnsupportedClassVersionError: PCHWRMServer/Main has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0


I suppose it would be possible to for me to compile it from source for ARMv6, but I have never compiled anything with Java before.  Thoughts?

**Comment by sgrayban** [comment]
Is it possible to recompile it so it works on the PI4 ? Or is this just not worth it?

**Comment by rnayabed** [comment]
I can trying making an armv6 binary. Even if you compile on the pi4 it
won't run :(

**Comment by sgrayban** [comment]
darn... i wonder if it will run on a headless pi if i ssh in and run it manually...

_Edit_... nope, does not run on a headless pi... pity, I was really hoping it would.

**Comment by rnayabed** [comment]
You should check out ModBros, they honestly have a better variant of this, but with web.. so you may feel it to be a bit sluggish

**Comment by bmxnate** [comment]
I smash read through some Java compiling how-to pages and gave it a try last night. The Zulu 11 JDK complained about a bunch of the lambda expressions in monitor.java and ended up failing with errors.

I'll see if I can find a version of openjdk that will run on armv6 today since I see that that is what your bundled jre is in the current armv7 release. This old pi has been sitting here doing absolutely nothing on my desk for quite some time, so now it's a matter of principle for me to get it up and running.

**Comment by bmxnate** [comment]
After much more reading, it is clear to me that the newest version of Java that will run on the Pi 0, Pi 0w, and Pi 1 is in fact Zulu 11.  With that in mind, I ssh'd into one of my Debian-based VMs and tried to compile with openjdk-11.  Below is an image of the errors that were encountered:

![snip](https://user-images.githubusercontent.com/63912193/79694859-2d236180-8241-11ea-84c7-26e3bc4ce09c.png)

I don't speak java very well at all, but this leads me to believe that some expression changes would have to be made to get this running on those older boards.

**Comment by rnayabed** [comment]
`->` in switch cases were introduced after java 11 so it cant compile in earlier java versions. Try using a zulu 14 one if available. or just hmu ill edit the source to support earlier java versions :) @bmxnate

**Comment by bmxnate** [comment]
Unfortunately, it looks like the source has to be edited for Java 11 since that is the newest release compatible with ARMv6 chips. If only Zulu 14 was available with ARMv6 support...

I certainly wouldn't have you edit the source code based solely on the fact that I don't have a Pi 2 or Pi 3 at my disposal, but the idea of this being able to run on a Pi 0w is pretty cool.

**Comment by rnayabed** [comment]
I have emailed bellsoft (i use their jdks in pi) to send an `armv6` version of their Liberica Full 14. Will share it with you when i get it :)

**Comment by bmxnate** [comment]
Sounds great. I have used Liberica before for various projects with good success and it is usually my go to for Pi 3 and Pi 4. I was bummed when I couldn't find anything from them for ARMv6.

**Comment by rnayabed** [comment]
Im going to merge this project to StreamPi as separate modules, that would be even better :)

**Comment by lejurassien** [comment]
Same error 
System.loadLibrary(glass_monocle) succeeded
* failed to add service - already in use?

It would be nice to make a package who's work with pi 4
You make a gooood job and i wish say thank you very much !!!
Have a nice day !!

**Comment by rnayabed** [comment]
It can run with Pi 4, but not in fb mode. It can run using xserver, with windows and performance impacts.

**Comment by jcordasco** [comment]
will you be rewriting the code to accommodate java 11? I'm just unclear if you will be ore if i need to buy a new pi.

**Comment by rnayabed** [comment]
no @jcordasco you can compile it with java 11 and run it yourself :)
