### ISSUE TITLE
"Failedto add service - already in use?"

### ISSUE THREAD

**Issue by BrennonTWilliams** [dubbadhar/PCHWRM_Server#21]
I set everything up on the PC fine, but on my Rasp Pi 4 running Raspian I get this result at ./run:

`JavaFX launchApplication method: launchMode=LM_CLASS
Prism pipeline init order: es2 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
System.loadLibrary(prism_es2_monocle) succeeded
	succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
System.loadLibrary(glass_monocle) succeeded
* failed to add service - already in use?
`

**Comment by cmatt4440** [comment]
I'm having the same issue. Have you learned anything?

**Comment by rnayabed** [comment]
You need to start it in x11 mode. Send over the content of the "run" file

**Comment by jdbinder** [comment]
same issue on fresh install - Run file contents below:

sudo jre/bin/java -Dembedded=monocle -Dglass.platform=Monocle -Dprism.order=es2 -Dmonocle.verbose=true -Dprism.verbose=true -Djavafx.verbose=true -cp PCHWRM_Server.jar PCHWRMServer.Main

**Comment by rnayabed** [comment]
Change the content of `run` file to :

```
sudo jre/bin/java -Djavafx.platform=gtk -Dprism.verbose=true -cp PCHWRM_Server.jar PCHWRMServer.Main
```

Also, make sure that your `/boot/config.txt` has the lines
`dtoverlay=vc4-fkms-v3d` & `gpu_mem=256`

This actually makes the software run on X11 instead of Framebuffer, with software rendering. Performance may be laggy.
