### ISSUE TITLE
Can’t get GUI

### ISSUE THREAD

**Issue by DueHack12** [dubbadhar/PCHWRM_Server#5]
Hello, I am using a raspberry pi 3 b and am only seeing text, is there a process that I am missing or is it not available?

**Comment by rnayabed** [comment]
Which screen are you using?

**Comment by DueHack12** [comment]
I am going in through vnc but I also plugged my Apple Cinema HD into it because that is the only HDMI screen I have right now

**Comment by alexxxdev** [comment]
I have the same problem on a 5 inch screen(HDMI 800x480)

**Comment by DueHack12** [comment]
Would you like a screenshot @dubbadhar ?

**Comment by rnayabed** [comment]
I recommend trying a full reinstall. Also make sure youre using only raspbian desktop

**Comment by DueHack12** [comment]
full reinstall of Raspbian or your software?

**Comment by rnayabed** [comment]
Raspbian

**Comment by DueHack12** [comment]
ok

**Comment by DueHack12** [comment]
Sorry it has been a while, after I did a full reinstall it worked, Thank you for your help

**Comment by rnayabed** [comment]
> Sorry it has been a while, after I did a full reinstall it worked, Thank you for your help
@DueHack12
https://i.kym-cdn.com/photos/images/original/001/226/823/8fd.jpeg
